# Guide:
# https://dev.to/pierresaid/deploy-node-projects-to-github-pages-with-github-actions-4jco
#
# Clojure:
# https://github.com/marketplace/actions/setup-clojure
#
name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false 

      - name: Set-up Clojure
        uses: DeLaGuardo/setup-clojure@2.0
        with:
          lein: 2.9.1

      - name: Install and Build ğŸ”§
        run: lein cljsbuild once prod

      - name: Make webDir dir
      - run: | 
        mkdir -p webDir
        cp index-prod.js webDir/index-prod.js
        cp index.html webDir/index.html

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: webDir


